export const day=[
    {
        dayName:"Sun",
        key:0
},
{dayName:"Mon",
key:0},
{dayName:"Tue",
key:0},
{dayName:"Wed",
key:0},
{dayName:"Thur",
key:0},
{dayName:"Fri",
key:0},
{dayName:"Sat",
key:0}];
export const month = ["January","February","March","April","May","June","July","August","September","October","November","December"];
export const options = {
    delete: "Delete",
    edit:"Edit",
    cancel: "Cancel",
  };
export const eventHeaders=
{
    title:"Title",
    description:"Description",
    starttime:" StartTime",
    endtime:"EndTime",
}
export const timeConstants=[
    {
        starttime:"00:00",
        endtime:"01:00",
        events:[]
    },
    {
        starttime:"01:00",
        endtime:"02:00",
        events:[]
    },
    {
        starttime:"02:00",
        endtime:"03:00",
        events:[]
    },
    {
        starttime:"03:00",
        endtime:"04:00",
        events:[]
    },
    {
        starttime:"04:00",
        endtime:"05:00",
        events:[]
    },
    {
        starttime:"05:00",
        endtime:"06:00",
        events:[]
    },
    {
        starttime:"06:00",
        endtime:"07:00",
        events:[]
    },
    {
        starttime:"07:00",
        endtime:"08:00",
        events:[]
    },
    {
        starttime:"08:00",
        endtime:"09:00",
        events:[]
    },
    {
        starttime:"09:00",
        endtime:"10:00",
        events:[]
    },
    {
        starttime:"10:00",
        endtime:"11:00",
        events:[]
    },
    {
        starttime:"11:00",
        endtime:"12:00",
        events:[]
    },
    {
        starttime:"12:00",
        endtime:"13:00",
        events:[]
    },
    {
        starttime:"13:00",
        endtime:"14:00",
        events:[]
    },
    {
        starttime:"14:00",
        endtime:"15:00",
        events:[]
    },
    {
        starttime:"15:00",
        endtime:"16:00",
        events:[]
    },
    {
        starttime:"16:00",
        endtime:"17:00",
        events:[]
    },
    {
        starttime:"17:00",
        endtime:"18:00",
        events:[]
    },
    {
        starttime:"18:00",
        endtime:"19:00",
        events:[]
    },
    {
        starttime:"19:00",
        endtime:"20:00",
        events:[]
    },
    {
        starttime:"20:00",
        endtime:"21:00",
        events:[]
    },
    {
        starttime:"21:00",
        endtime:"22:00",
        events:[]
    },
    {
        starttime:"22:00",
        endtime:"23:00",
        events:[]
    },
    {
        starttime:"23:00",
        endtime:"24:00",
        events:[]
    },
]